version: '3'

services:

  nodejs-curriculo:
    container_name: nodejs-curriculo
    build: '.'
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    depends_on:
      - postgres-curriculo
      - mongo-curriculo
    networks:
      - app-curriculo
    ports:
      - '3333:3333'

  mongo-curriculo:
    container_name: mongo-curriculo
    image: 'mongo'
    restart: unless-stopped
    volumes:
      - mongo-curriculo-data:/data
    ports:
      - '27017:27017'
    networks:
      - app-curriculo

  postgres-curriculo:
    container_name: postgres-curriculo
    image: postgres:11
    restart: unless-stopped
    volumes:
      - postgres-curriculo-data:/data
    environment: 
      POSTGRES_DB: ${TYPEORM_HOST}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD} 
    networks:
      - app-curriculo

volumes:
  postgres-curriculo-data:
  mongo-curriculo-data:

networks:
  app-curriculo:
      driver: bridge