version: '3'

services:

  nodejs-curriculo:
    container_name: nodejs-curriculo
    build: '.'
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    depends_on:
      - postgres-curriculo
      - mongo-curriculo
    networks:
      - app-curriculo
    ports:
      - '3333:3333'
    environment:
      # DATABASE_URL: postgres://postgres:docker@postgres-curriculo:5432/curriculo
      DATABASE_URL: ${DATABASE_URL} 
      PERSISTENCE_TYPE: postgres

  mongo-curriculo:
    container_name: mongo-curriculo
    image: 'mongo'
    restart: unless-stopped
    volumes:
      - mongo-curriculo-data:/data
    ports:
      - '27017:27017'
    networks:
      - app-curriculo

  postgres-curriculo:
    container_name: postgres-curriculo
    image: postgres:11
    restart: always
  
    volumes:
      - postgres-curriculo-data:/data
      # - ./pgdata:/var/lib/postgresql/data
      - ./dbscripts/postgres:/docker-entrypoint-initdb.d

    environment:
        POSTGRES_USER: ${TYPEORM_USERNAME}
        POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
        POSTGRES_DB: ${TYPEORM_DATABASE} 
        # POSTGRES_USER: postgres
        # POSTGRES_PASSWORD: docker
        # POSTGRES_DB: curriculo
    ports:
      - "5432:5432"
    networks:
      - app-curriculo

volumes:
  postgres-curriculo-data:
  mongo-curriculo-data:

networks:
  app-curriculo:
      driver: bridge